export default {
  errors: {
    connectionError: 'Error de conexión',
    pageNotFound: 'Página no encontrada',
    phError: 'Ocurrió un error al obtener el pH',
    temperatureError: 'Ocurrió un error al obtener la Temperatura',
    getAlertsError: 'Oucrrió un error al tratar de obtener las alertas',
    createAlertError: 'Oucrrió un error al tratar de crear la alerta',
    updateAlertError: 'Oucrrió un error al tratar de actualizar la alerta',
    deleteAlertError: 'Oucrrió un error al tratar de borrar la alerta',
  },
  actions: {
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    ok: 'OK',
  },
  messages: {
    alertSaved: '¡Alerta guardada con éxito!',
    alertUpdated: '¡Alerta actualizada con éxito!',
    alertDeleted: '¡Alerta borrada con éxito!',
  },
  home: {
    phAverage: 'pH Promedio',
    temperatureAverage: 'Temperatura Promedio',
    maxValue: 'Valor Máximo',
    manageAlert: 'Gestionar alerta',
    managePhAlert: 'Gestionar alerta de pH',
    manageTemperatureAlert: 'Gestionar alerta de Temperatura',
    phValue: 'Valor del pH',
    temperatureValue: 'Valor de la Temperatura',
    alertDialog: {
      alertDescription: 'Ingrese el valor de la alerta, el cual el sistema tomara como referencia para que en el momento en el que sea alcanzado o superado le sea notificado vía correo electrónico.',
    },
  },
  generateReport: {
    loadingDocument: 'Cargando Documento...',
    downloadNow: '¡Descargar Ahora!',
    ph: 'pH',
    average: 'Promedio',
    maxValue: 'Valor Máximo',
    time: 'Tiempo',
    temperature: 'Temperatura',
    fermentationProcess: 'Proceso de Fermentación',
  },
};
